# Generated by Django 5.0.7 on 2024-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='')),
                ('founded_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'sector',
                    models.CharField(
                        choices=[
                            ('tech', 'Technology'),
                            ('finance', 'Finance'),
                            ('health', 'Health'),
                            ('education', 'Education'),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
