# Generated by Django 5.0.7 on 2024-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('general', '0002_company_delete_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to='logos/'),
        ),
    ]
